theme: jekyll-theme-minimal
logo: gfarnadi.github.io/portrait.png
google_analytics: UA-9578462-2
title: Golnoosh Farnadi
description: Assistant Professor at HEC Montréal \n Adjunt Professor at University of Montreal \n Core Faculty Member at MILA \n CANADA CIFAR AI Chair holder \n working on fairness in Machine learning, AI and decision making

