#theme: minima
#logo: portrait.png
#google_analytics: UA-9578462-2
title: <a href="https://denafiroozi.github.io/DF/">Instructor &#58; Dena Firoozi</a>
description: Assistant Professor at HEC Montréal


