#theme: minima
#logo: portrait.png
#google_analytics: UA-9578462-2
title: <a href="https://jian-tang.com/">Instructor &#58; Jian Tang, Associate Professor at HEC Montréal</a>
#description: Associate Professor at HEC Montréal


