theme: jekyll-theme-minimal
logo: gfarnadi.github.io/portrait.png
google_analytics: UA-9578462-2
title: Golnoosh Farnadi
description: |
- **Assistant Professor at HEC Montréal**
- **Adjunt Professor at University of Montreal**
- **Core Faculty Member at MILA**
- **CANADA CIFAR AI Chair holder**


