theme: jekyll-theme-minimal
logo: gfarnadi.github.io/portrait.png
google_analytics: UA-9578462-2
title: Golnoosh Farnadi
description: Postdoctoral Fellow at Mila, working on fairness in Machine learning, AI and decision making
#AI #MachineLearning #FairAI
